# Build Mailhog with go 16
FROM golang:1.16.9-alpine as builder

RUN apk --no-cache add --virtual build-dependencies git
RUN cd /go && export GO111MODULE=off && \
    go get github.com/mailhog/MailHog

# Final image is based on latest alpine to be as small as possible
FROM alpine

# Install stunnel  
RUN apk add --no-cache stunnel
# Prepare layout
RUN mkdir -p /etc/stunnel 

# Provision assets and make executable
COPY docker-entrypoint.sh /etc/docker-entrypoint.sh
COPY stunnel.conf /etc/stunnel/stunnel.conf
COPY --from=builder /go/bin/MailHog /etc/mailhog/mailhog
RUN chmod +x /etc/docker-entrypoint.sh \
  && chmod +x /etc/mailhog/mailhog \
  && ln -s /etc/mailhog/mailhog /bin/mailhog \
  && ln -s /etc/docker-entrypoint.sh /bin/docker-entrypoint.sh 

# Configure ENV
ENV CAROOT /var/certs
ENV MH_UI_WEB_PATH mailhog
ENV MH_HOSTNAME mailhog

# 465 for start tls, 8025 for http only web UI
EXPOSE 465 1025 8025

# Use custom launcher: starts both mailhog and stunnel to provide secured smtp  
ENTRYPOINT ["docker-entrypoint.sh"]

# Note: this is for internal test only: we use root user 