FROM golang:alpine as forge

# Install MailHog:
RUN apk --no-cache add --virtual build-dependencies \
    git \
  && mkdir -p /root/go \
  && export GOPATH=/root/go \
  && go get github.com/mailhog/MailHog

FROM alpine

# Install stunnel
RUN apk add --no-cache stunnel

# Prepare layout
RUN mkdir -p /opt/mailhog/{bin,run} \
  && adduser -D -u 1000 mailhog \
  && chown -R mailhog:mailhog /opt/mailhog 

COPY --from=forge /root/go/bin/MailHog /usr/local/bin/

ENV CAROOT /var/certs
ENV MH_UI_WEB_PATH mailhog
ENV MH_HOSTNAME localhost

#USER mailhog
#WORKDIR /home/mailhog

# Expose the SMTP and HTTP ports:
EXPOSE 425 1025 8025

ENTRYPOINT ["docker-entrypoint.sh"]
#CMD ["stunnel"]
