FROM golang:1.16.9 as builder

RUN cd /go && \
    go get -u github.com/mailhog/MailHog && \
    ls -lsah src/github.com/mailhog && \
    cd src/github.com/mailhog/MailHog && \
    go build -o /bin/mailhog

FROM alpine

# Install stunnel  
RUN apk add --no-cache stunnel

# Prepare layout
RUN mkdir -p /etc/stunnel 
COPY docker-entrypoint.sh /bin/docker-entrypoint.sh
COPY stunnel.conf /etc/stunnel/stunnel.conf
COPY --from=builder /bin/mailhog /bin/mailhog

RUN chmod +x /bin/docker-entrypoint.sh \
  && chmod +x /bin/mailhog

ENV CAROOT /var/certs
ENV MH_UI_WEB_PATH mailhog
ENV MH_HOSTNAME mailhog

# Expose the SMTP and HTTP ports:
EXPOSE 465 1025 8025

ENTRYPOINT ["docker-entrypoint.sh"]
