version: '3.7'

services:
    
    certs:
        image: pydio/custom-images:mkcert-0.9.0
        volumes:
            - ./certs:/var/certs
        environment:
            - DOMAINS=mailhog,cells
            
    mailhog:
        image: pydio/custom-images:mailhog-0.9.0    
        hostname: mailhog
        volumes:
            - ./certs:/var/certs
