version: '3.7'

services:
    
    certs:
        image: pydio/images:mkcert-1.0.0
        volumes:
            - ./certs:/var/certs
        environment:
            - DOMAINS=mailhog,cells
            
    mailhog:
        image: pydio/images:mailhog-1.0.0
        hostname: mailhog
        volumes:
            - ./certs:/var/certs
