# Build mkcert binary in another bigger container intrumented with go, git,...
FROM golang:1.16.9 as builder

RUN cd /go && \
  go install filippo.io/mkcert@v1.4.3

FROM busybox:glibc
COPY --from=builder /go/bin/mkcert /var/mkcert/bin/mkcert
COPY docker-entrypoint.sh /bin/docker-entrypoint.sh

# Final configuration
RUN ln -s /var/mkcert/bin/mkcert /bin/mkcert &&\
    chmod +x /bin/docker-entrypoint.sh && chmod +x /var/mkcert/bin/mkcert
WORKDIR /var/certs
ENV CAROOT /var/certs

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["mkcert"]
