# Build mkcert binary using the latest Debian image from the golang Docker repo
#   instrumented with go, git, etc.
FROM golang:1.19 as builder

RUN cd /go && \
  go install filippo.io/mkcert@v1.4.4

FROM busybox:glibc
COPY --from=builder /go/bin/mkcert /var/mkcert/bin/mkcert
COPY docker-entrypoint.sh /bin/docker-entrypoint.sh

# Final configuration
RUN ln -s /var/mkcert/bin/mkcert /bin/mkcert &&\
    chmod +x /bin/docker-entrypoint.sh && chmod +x /var/mkcert/bin/mkcert
WORKDIR /var/certs
ENV CAROOT /var/certs

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["mkcert"]
